### ISSUE TITLE
License violation

### ISSUE THREAD

**Issue by Cvolton** [SevenworksDev/DeadHack#1]
GPL v3 mandates that you provide a copy of the source code with any binary releases of your software or provide an easy way for anyone to get it if they want it. Since said source code doesn't seem to be offered apart from the `main.py` file, which just appears to download binary blobs from this exact repository, I believe that this repository is in strong violation of its own license and that I have been stripped of the freedoms I have been promised by said license. Thank you, I hope for a positive resolution of this issue

**Comment by TechStudent10** [comment]
+1 I agree with everything stated here

**Comment by dankmeme01** [comment]
there is no way im gonna miss this
dude , u r rylixmods ver 2

**Comment by SevenworksDev** [comment]
> GPL v3 mandates that you provide a copy of the source code with any binary releases of your software or provide an easy way for anyone to get it if they want it.

deadHack is pretty much all my programs that I have released publicly here and on my Discord Server (i removed license in case ive missed one) but compiled using PyInstaller so I do provide source code.

> there is no way im gonna miss this
> dude , u r rylixmods ver 2

this statement has been proven to be True by american patriots
